name: Process Figma Tokens PR

on: pull_request

jobs:
  run_if: 
    if: ${{ github.head_ref = 'figma-tokens' }}
    name: Process Figma Tokens
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout to master
        uses: actions/checkout@master
        with: 
          repository: ${{ github.event.pull_request.head.repo.full_name}}
          ref: ${{ github.event.pull_request.head.ref}}

      - name: Install Dependencies
        run: npm install

      - name: Run token-transformer
        run: npx token-transformer tokens/tokens.json tokens/sd-input-tokens.json --resolveRefences false

      - name: Run style-dictionary
        run: npx style-dictionary build --config config.json

      - name: Commit changes
        use: EndBug/add-and-commit@v9
        with:
          author_name: Summer
          author_email: dxq3442@gmail.com
          message: 'chore: style-dictionary output'
          add: '.'

